### ISSUE TITLE
Web GUI

### ISSUE THREAD

**Issue by jbernsie** [jbernsie/enkee#2]
Build a web GUI that uses `libenkee` to perform the same operations as the CLI app
inside of a modern web interface. This could lead to some interesting features.

Currently being tracked in [feature/web-gui](https://github.com/jbernsie/enkee/tree/feature/web-gui) branch

- [daemonize](http://knsd.github.io/daemonize/daemonize/index.html)
- [rocket](https://rocket.rs/)

### TODO

- [x] Create `src/bin/web_daemon.rs`
- [x] Add rocket as a dependency
- [x] Create base layout for rocket web app
- [x] Wrap server code in a clap CLI
- [x] Add Sqlite db adapter
- [x] Pass the database file to the server
- [x] Once decrypted, a view loads the records
- [ ] Implement start and stop commands that control the daemon process
- [ ] Put the web GUI behind an compilation flag (cargo feature)
- [ ] Add actual management actions to the GUI
